language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

install:
  - go get -v github.com/morbz/gosmonaut

script:
  - make cover

after_success:
  - go get -u github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
